version: "3.13"
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: application:django
    container_name: app_container
    command: gunicorn redis_project.wsgi:application --bind 0.0.0.0:8000