# Generated by Django 5.0.1 on 2024-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dweetapp', '0002_alter_dweet_options_dweet_like'),
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dweet',
            name='like',
        ),
        migrations.AddField(
            model_name='dweet',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='profileapp.profiles'),
        ),
    ]
