# Generated by Django 5.0.1 on 2024-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dweetapp', '0003_remove_dweet_like_dweet_like'),
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to='profileapp.profiles'),
        ),
    ]
