# Generated by Django 2.2 on 2024-02-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dweetapp', '0005_alter_dweet_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dweet', to='twitterapp.UserProfile'),
        ),
    ]
