# Generated by Django 5.0.1 on 2024-02-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='friend_request',
            field=models.ManyToManyField(blank=True, related_name='requested_by', to='profileapp.profiles'),
        ),
    ]
