# Generated by Django 5.0.1 on 2024-02-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dweet',
            new_name='comment',
        ),
    ]
