# Generated by Django 5.0.1 on 2024-02-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0002_rename_dweet_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='dweet',
        ),
    ]
